CREATE DATABASE IF NOT EXISTS web_security;
USE web_security;
CREATE TABLE IF NOT EXISTS users (
    userId INT AUTO_INCREMENT PRIMARY KEY,
    userName VARCHAR(100) NOT NULL,
    userSurname VARCHAR(100) NOT NULL,
    userPassword VARCHAR(255) NOT NULL,
    userEmail VARCHAR(100) NOT NULL
);
